<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\K1QuickGen.Domain\K1QuickGen.Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="RabbitMQ.Client" Version="6.4.0" />
    <PackageReference Include="NLog" Version="5.2.0" />
    <PackageReference Include="QuestPDF" Version="2024.3.0" />
  </ItemGroup>
</Project>
