<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\K1QuickGen.Contracts\K1QuickGen.Contracts.csproj" />
    <ProjectReference Include="..\K1QuickGen.Domain\K1QuickGen.Domain.csproj" />
  </ItemGroup>
</Project>
