<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\K1QuickGen.Api\K1QuickGen.Api.csproj" />
    <ProjectReference Include="..\K1QuickGen.Contracts\K1QuickGen.Contracts.csproj" />
  </ItemGroup>

</Project>
